spelling

diff --git a/bin/admin_mode b/bin/admin_mode
--- a/bin/admin_mode
+++ b/bin/admin_mode
@@ -34,7 +34,7 @@ admin_mode() {
     fi
     try=$((try+1))
   done
-  echo "$(gettext "Error: wrong password")" >&2
+  echo "$(gettext "Error: wrong password.")" >&2
   return 1
 }
 
