cleaning _gsh_save so that it works correctly when explicitly called

diff --git a/scripts/_gsh_save b/scripts/_gsh_save
--- a/scripts/_gsh_save
+++ b/scripts/_gsh_save
@@ -18,12 +18,12 @@ then
   exit 2
 fi
 
-case "$(cd "$(dirname "$SAVEFILE")"; pwd -P)" in
-  "$GSH_ROOT"*)
-    echo "Error: the savefile cannot be inside GameShell directory structure." >&2
-    exit 4
-    ;;
-esac
+# case "$(cd "$(dirname "$SAVEFILE")"; pwd -P)" in
+#   "$GSH_ROOT"*)
+#     echo "Error: the savefile cannot be inside GameShell directory structure." >&2
+#     exit 4
+#     ;;
+# esac
 
 
 if ! [ -r "$GSH_ROOT" ]
@@ -41,14 +41,14 @@ fi
 GSH_LAST_CHECKED_MISSION=$(_gsh_plm)
 sed-i "s/^GSH_LAST_CHECKED_MISSION=.*/GSH_LAST_CHECKED_MISSION=$GSH_LAST_CHECKED_MISSION/" "$GSH_ROOT/lib/header.sh"
 
-tar -zcf "$GSH_ROOT.tgz" -C "$GSH_EXEC_DIR" "$(basename "$GSH_ROOT")"
+tar --exclude="$SAVEFILE.tgz" -zcf "$SAVEFILE.tgz" -C "$(dirname "$GSH_ROOT")" "$(basename "$GSH_ROOT")"
 ARCHIVE_OK=$?
 
-cat "$GSH_ROOT/lib/header.sh" "$GSH_ROOT.tgz" > "$SAVEFILE"
+cat "$GSH_ROOT/lib/header.sh" "$SAVEFILE.tgz" > "$SAVEFILE"
 SAVE_OK=$?
 chmod +x "$SAVEFILE"
 
-rm -f "$GSH_ROOT.tgz"
+rm --system -f "$SAVEFILE.tgz"
 
 if [ "$ARCHIVE_OK" -ne 0 ] || [ "$SAVE_OK" -ne 0 ]
 then
